[build]
builder = "dockerfile"
dockerfilePath = "worker/Dockerfile"
watchPatterns = ["worker/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "always"
numReplicas = 1
